export const data = [
  {
    category: 'Animals',
    type: 'boolean',
    difficulty: 'easy',
    question: `A slug's blood is green.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Film',
    type: 'boolean',
    difficulty: 'easy',
    question: `The movie 'The Nightmare before Christmas' was all done with physical objects.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Geography',
    type: 'boolean',
    difficulty: 'easy',
    question: 'Greenland is almost as big as Africa.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'easy',
    question: `The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'easy',
    question: 'Gumbo is a stew that originated in Louisiana.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: `The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: `'Half-Life 2' runs on the Source Engine.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'In Kill La Kill, the weapon of the main protagonist is a katana. ',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: `In 'Sonic Adventure', you are able to transform into Super Sonic at will after completing the main story.`,
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Science & Nature',
    type: 'boolean',
    difficulty: 'easy',
    question: 'An atom contains a nucleus.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Politics',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'Russia passed a law in 2013 which outlaws telling children that homosexuals exist.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'easy',
    question: 'No Game No Life first aired in 2014.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: `In 'Sonic Adventure', you are able to transform into Super Sonic at will after completing the main story.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'History',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'The United States of America declared their independence from the British Empire on July 4th, 1776.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Comics',
    type: 'boolean',
    difficulty: 'easy',
    question: `The 'Pepe' meme originated from a comic drawn by Matt Furie called 'Boy's Club'?`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'easy',
    question: `The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'In Pokemon Sun and Moon, a male Salandit can evolve to a Salazzle.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Sports',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Science: Computers',
    type: 'boolean',
    difficulty: 'easy',
    question: 'Linux was first created as an alternative to Windows XP.',
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'easy',
    question: `Scatman John's real name was John Paul Larkin.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: `'Metal Gear Solid 3: Snake Eater' was released in 2004.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Geography',
    type: 'boolean',
    difficulty: 'easy',
    question: `Hungary is the only country in the world beginning with H.`,
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'easy',
    question: `In the 'To Love-Ru' series, Golden Darkness is sent to kill Lala Deviluke.`,
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'History',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Science & Nature',
    type: 'boolean',
    difficulty: 'easy',
    question: `Water always boils at °C, °F, 373.15K, no matter where you are.`,
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'easy',
    question: `The 2011 movie 'The Adventures of Tintin' was directed by Steven Spielberg.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Science: Mathematics',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'An isosceles triangle has two sides of equal length as opposed to three.',
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Television',
    type: 'boolean',
    difficulty: 'easy',
    question: `'The Simpsons' family is named after creator Matt Groening's real family.`,
    correct_answer: 'True',
    incorrect_answers: ['False'],
  },
  {
    category: 'Entertainment: Books',
    type: 'boolean',
    difficulty: 'easy',
    question: `Shub-Niggurath is a creature that was created by \tJ. R. R. Tolkien in his novel 'The Lord of The Rings'.`,
    correct_answer: 'False',
    incorrect_answers: ['True'],
  },
];

export const buttonOptions = [
  {
    id: 1,
    text: 'True',
    backgroundColor: '#4fbd1b',
  },
  {
    id: 2,
    text: 'False',
    backgroundColor: '#e04e10',
  },
];
